spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auction?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: rencai
#    password: RENcai123.
    username: root
    password: root
    view:
        prefix: /static/
  mvc:
    static-path-pattern: /static/images/
  resources:
    static-locations: static/
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

server:
  port: 8088
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.auction.model